### PR TITLE
Byte comp3

### PR DESCRIPTION
**Pull request by jschaf**
I think this is about the end of the easy fixes.  Now for the fun stuff.

### CODE REVIEW

**Comment by jkitchin** [comment]
What kind of fun stuff do you have in mind!

**Comment by jschaf** [comment]
I'd like to overhaul the HTML output.  I have to do some pretty gross hacks to customize output currently, like override a defun that's generated by a macro.  https://github.com/jschaf/org-tufte-blog/blob/master/otb.el#L914

I'll create a work-in-progress pull request to flesh out the details.

**Comment by jkitchin** [comment]
you may want to checkout https://github.com/jkitchin/org-ref/tree/master/citeproc. It is a potentially more powerful approach to exporting citations. It has a ways to go, but is basically functional.

Thanks for your help on org-ref. I learned a few new things today!

**Comment by jkitchin** [comment]
Do you have some html out there that currently uses org-ref? The link on your github page (http://jschaf.com) doesn't show anything.

**Comment by jschaf** [comment]
ah, I should update my profile.  I moved over to http://delta46.us.  Here's an example that uses it, http://delta46.us/somalia-instability/.  I use a pretty customized version of org-export.  The side-notes are all genereated from a bib file at https://github.com/jschaf/blog-redux/blob/master/posts/somalia.bib

**Comment by jkitchin** [comment]
That is pretty nice! I am glad someone else in the world is making use of org-ref.

**Pull request merged**
