### PR TITLE
ENH: download Copernicus journals' PDFs with doi-utils

### PR DESCRIPTION
**Pull request by andreas-h**
Add support for downloading PDFs from Copernicus Publications journals to doi-utils.

PDF URL is hidden in the HTML page, so I copied the Science-Direct solution.  Since Copernicus has many journals, I created a new list to identify these.

This is actually my first elisp contribution ever, so please bear with me in case I did something stupid ...

### CODE REVIEW

**Comment by andreas-h** [comment]
Mhh, actually it's not working yet.  The `copernicus-pdf-url` function returns the url of the PDF, but then I get

    url-retrieve-internal: Wrong type argument: char-or-string-p, ("https://www.geosci-model-dev.net/10/609/2017/gmd-10-609-2017.pdf")

I'm sure it's something simple, but I cannot seem to figure out how to solve this.  I'd appreciate any help!

**Comment by jkitchin** [comment]
it looks like you are getting a list not a string perhaps.

**Comment by andreas-h** [comment]
Thanks. So apparently the `loop` macro always yields a list. Seems to work for me, now.

**Comment by jkitchin** [comment]
Sure, when you use collect in the loop!

**Pull request merged**
