### PR TITLE
Return matches instead of nil Fixes: https://github.com/jkitchin/org-ref/issues/410

### PR DESCRIPTION
**Pull request by jagrg**

### CODE REVIEW

**Comment by jkitchin** [comment]
I am a little surprised this was needed. I thought the append function would return the same thing. Do you know why it didn't?

**Comment by jagrg** [comment]
The append function returns nil. In the old way, assuming you have one label defined (e.g. label:test), if you eval `(org-ref-get-labels)` you get `("test" nil)`. Now you get `("test")`. cc: @andreaskiermeier.

**Comment by jkitchin** [comment]
That doesn't sound right. The doc string reports:

(append &rest SEQUENCES)

Concatenate all the arguments and make the result a list.
The result is a list whose elements are the elements of all the arguments.

```
#+BEGIN_SRC emacs-lisp
(append '(1 2) '(3 4) nil)
#+END_SRC

```
```
#+RESULTS:
| 1 | 2 | 3 | 4 |
```

**Comment by jagrg** [comment]
You're right, it's not the append function. The nil is coming from `org-ref-get-names`.

**Comment by jkitchin** [comment]
that is true. that is a bug in that function, it was using the wrong match.

**Pull request merged**
