### PR TITLE
Byte comp2

### PR DESCRIPTION
**Pull request by jschaf**
More byte compiler fixes.  I grouped fixes by the type of fix.  If you'd prefer them squashed into one commit, lemme know.

### CODE REVIEW

**Comment by jkitchin** [comment]
Do you know how I can fetch these to a local branch, and apply the commits that are good, or revert the ones that aren't? 

or would it be better to modify the pull request until I just merge it?

**Comment by jschaf** [comment]
You can fetch a PR with https://help.github.com/articles/checking-out-pull-requests-locally/

I'm not sure whats failing.  I'm happy to make changes as needed, I just can't figure out what broke.

**Comment by jkitchin** [comment]
Ok, thanks for all the comments. I haven't been byte-compiling anything, but I should probably start. I merged these by cherry-picking them in. Github doesn't seem to notice that, so I am going to close this request.

It seems that something changed in the travis-ci build process and I have to modify the makefile for it to pass.

**Comment by jschaf** [comment]
Check out https://github.com/flycheck/flycheck.  It will give you warnings and compilation errors in real-time for elisp code.

**Comment by jkitchin** [comment]
Thanks. It does some odd things,
It flags this and says it cannot load it. 
(require 'dash) 

I guess this is related to this warning when I try to byte compile some files:
arxiv.el:229:1:Warning: the function `-remove-last' is not known to be
    defined.

**Pull request closed without merging**
