### PR TITLE
Update glossary links v9

### PR DESCRIPTION
**Pull request by jagrg**
I haven't done anything with face or tooltip.

### CODE REVIEW

**Comment by jkitchin** [comment]
I think it would make sense to integrate the face and tooltip code in this PR. are you planning to do that?

**Comment by jagrg** [comment]
There's a hook on line 309 that adds the face, so I wasn't sure if that was needed at this point. For tooltip, do we just add: `:face-help 'or-glossary-tooltip`? I can add those too if you want.

**Comment by jkitchin** [comment]
I think it should be :help-echo.

I would remove the hook code, and add :face org-ref-glossary-face to the link definitions. We can also remove or-next-glossary-link, or move it into a conditional statement to maintain org8 functionality.

**Comment by jagrg** [comment]
Done.

**Pull request merged**
