### PR TITLE
[WIP] Update testing

### PR DESCRIPTION
**Pull request by jabranham**
This updates the testing environment to check with Emacs 25.3 and the 26 pretest. It also adds a test that ensures org-ref compiles without warnings (which will fail as of the moment, I believe)

### CODE REVIEW

**Comment by jabranham** [comment]
Two remaining issues: 

1. the MELPA download seems to fail on the Emacs-26-pretest and Emacs-git versions, I don't know why

2. the compile command needs to be told to compile only the org-ref files instead of compiling all the packages pulled in as dependencies, which may have byte compiler warnings of their own.

**Comment by jabranham** [comment]
Ok I've updated the build environment but it seems like cask doesn't issue the correct exit codes for a build failure: https://github.com/cask/cask/pull/351

**Comment by jkitchin** [comment]
Thanks for working on this. It looks like it is good now. I updated the travis to use the old image. The new change they made was not building emacs well. Is there anything else you still consider WIP?

**Comment by jabranham** [comment]
It should be OK to merge. Ideally I'd like it to error on byte compiler warnings, but that doesn't seem easy to do with cask as of now.

**Pull request merged**
