### PR TITLE
Split function

### PR DESCRIPTION
**Pull request by jagrg**
https://github.com/jkitchin/org-ref/pull/612

### CODE REVIEW

**Comment by jagrg** [comment]
> I'm not sure I understand the motivation for the when clause at the end of orcb-fix-spacing.

The when clause checks if the point is in a comment line or closing bracket, and if it is, it adds a new line without deleting comments as the old code did.

> Also, picking nits, I think that most of the cleaning functions are marked (interactive).

AFAIU cleaning functions are not interactive. They should be added or removed from the org-ref-clean-bibtex-entry-hook hook and run when the org-ref-clean-bibtex-entry command is called.

**Comment by treese** [comment]
That all seems fine. Thanks for the work.

**Comment by jkitchin** [comment]
I think it is fine if the cleaning functions are interactive, that makes them easy to test in an entry, and to run in one-off cleaning needs. It is not critical though, and is fine if they aren't.

**Comment by jagrg** [comment]
Yes, it returns t if the point is at the end of the line, but in an empty line (see "|" above) it also returns t. It should return nil. Otherwise it adds an extra line that shouldn't be there. Change the last part of the function to:

```
(when (comment-only-p (line-beginning-position) (line-end-position))
  (end-of-line)
  (newline))
```

**Pull request merged**
