### PR TITLE
Generate a conventional elisp-only package.

### PR DESCRIPTION
**Pull request by divinenephron**
The Makefile in this pull request tangles every org file to elisp then puts these and the other elisp files into a package using Cask. Having this build process will allow developers to use literate programming, while package users will get the benefits of plain elisp files (such as speed from byte compilation).

People who download the source can load files as described in `README.org`. Package users should be able to activate org-ref with:

```emacs-lisp
(require 'org-ref)
```

They will have to `require` other files separately (e.g. `doi-utils`).

This still isn't enough to [submit a package to MELPA][1]. Autoload magic comments need to be added (see `(info "(elisp) Packaging")`) and somebody needs to test the package builds and installs.

[1]: https://github.com/milkypostman/melpa#contributing-new-recipes

### CODE REVIEW

**Comment by jkitchin** [comment]
How do you choose what to "autoload"? there are 92-ish defund in org-ref.el for example.

**Comment by jkitchin** [comment]
Thanks by the way for pushing this towards packaging!

**Comment by divinenephron** [comment]
Sebastien Wiesner summarsied [which functions to autoload][1] as:

> - definitions of major and minor modes,
> - interactive commands by which a user would start to use a specific package (e.g. gnus, erc, magit-status, etc.),
> - and interactive commands which provide generic utilities, e.g. occur, find, ace-jump-mode, etc.
> 
> [...]
> 
> If your package should automatically register itself in specific Emacs extension points, you should add autoloads for these as well, to make sure that they are evaluated during package initialization. A typical example is adding a mode to auto-mode-alist:

[1]: http://www.lunaryorn.com/2014/07/02/autoloads-in-emacs-lisp.html

You're much better placed than I to determine which parts of org-ref fit into these categories.

Since we're putting this into a package, we're required to use the [autoload magic comment][2] method of autoloading (Wiesner calls these autoload cookies, but the [Emacs manual][3] calls them magic comments).

[2]: http://www.lunaryorn.com/2014/07/02/autoloads-in-emacs-lisp.html#autoload-cookies
[3]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html

**Comment by jkitchin** [comment]
ok, thanks for the links. At the moment there are three auto loads. There are still 50 more interactive commands, but I suppose they aren't really generic.

**Pull request merged**
